### ISSUE TITLE
Eclipse Plugin Opening Model File

### ISSUE THREAD

**Issue by pluxain** [telosys-tools-bricks/telosys-tools-dsl-parser#3]
Hi,

I currently try to use the Telosys Eclipse plugin. It is like there is a problem between creating a Model folder and retrieving it in the Telosys Editor within Eclipse.

Creating the folder works correctly (the folder is correctly created in the correct location set in "Models folder" in the Telosys Settings -> General) but when the Editor tries to open it I get en Exception. It seems the absolute path uses the eclipse "Workspace location" and recreate the path from there using the `WorkspaceLocation/Project Name/TelosysTools/ModelFolder` instead of the "Models folder". For some reason on my environment the project I use Telosys in is not included in the eclipse workspace folder.

I tried to simply create a shortcut on Windows to point the correct folder in the correct location Telosys Plugin tries to retrieve but it does not work.

Can I provide you more informations ? Is it possible to fix this with the `telosys-tools.cfg` file ?

**Comment by l-gu** [comment]
Bug fixed in ver 3.1.2
