### ISSUE TITLE
support multiple inheritance or traits 

### ISSUE THREAD

**Issue by shusson** [telosys-tools-bricks/telosys-tools-dsl-parser#4]
I wasn't sure where to add this feature request, but this seemed repository seemed appropriate.

Are there any plans to support multiple inheritance or traits in the entity definition?

Something like:
```
Location {
    lat: double;
    long: double;
}

Landmark {
    website: string;
    name: string;
}

Library extends Location, Landmark {
    books : Book[];
}

```

**Comment by l-gu** [comment]
Since Telosys 4.0 you can use **@Extends** annotation at entity level
( see https://doc.telosys.org/dsl-model/annotations )
