### ISSUE TITLE
Adding some properties on Entity level to help with inheritance concrete type and introducing Guid entity type

### ISSUE THREAD

**Issue by radrad** [telosys-tools-bricks/telosys-tools-dsl-parser#5]
As mentioned in a stackoverflow question: 
Regarding the class, for the moment there are no annotations (or tags) at the entity level (**it will happen soon**). But you can use a file to define the entities which should extend another class.

https://stackoverflow.com/questions/70092361/generating-class-in-c-sharp-that-inherits-a-generic-class-which-uses-type-parame/70123996#70123996
I wanted to express the fact that the Country class inherits from an entity and that it has an Id of Guid type.

    public class Country : Entity<Guid>
    {

    }

    public abstract class Entity<TKey> : Entity, IEntity<TKey>
    {
        public virtual TKey Id { get; protected set; }
        protected Entity(TKey id)
        {
            Id = id;
        }
    }

Next I am missing Guid property type which should be a fairly frequent type in modern language.
It should be added to the existing list:
  . binary
  . boolean
  . byte
  . date
  . decimal
  . double
  . float
  . int
  . long
  . short
  . string
  . time
  . timestamp

**Comment by l-gu** [comment]
Annotations and tags at entity level are available since **Telosys 4.0**
